### ISSUE TITLE
Reset command uses removed find_all_data_paths() method

### ISSUE THREAD

**Issue by markgw** [markgw/pimlico#16]
Reset command uses removed find_all_data_paths() method from pipeline config that was removed in the recent change to data storage locations.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/magranro/code/langsim/pimlico/src/python/pimlico/cli/main.py", line 218, in <module>
    opts.func(pipeline, opts)
  File "/home/magranro/code/langsim/pimlico/src/python/pimlico/cli/reset.py", line 51, in run_command
    module.reset_execution()
  File "/home/magranro/code/langsim/pimlico/src/python/pimlico/core/modules/base.py", line 915, in reset_execution
    for path in self.pipeline.find_all_data_paths(self.get_module_output_dir()):
AttributeError: 'PipelineConfig' object has no attribute 'find_all_data_paths'
```

**Comment by markgw** [comment]
Fixed by 7d63724
